apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonarqube
  template:
    metadata:
      name: sonarqube
      labels:
        name: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:8.2-community
          env:
            - name: "SONARQUBE_JDBC_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_jdbc_user
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_jdbc_pwd
          ports:
            - name: sonarqube
              containerPort: 9000
          resources:
            requests:
              memory: 2000Mi
            limits:
              memory: 2000Mi
      initContainers:
        - name: sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
      nodeSelector:
        dedicatedfor: sonarqubeapp
