apiVersion: v1
kind: Service
metadata:
  name: sonarqube-loadbalance-service
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    name: sonarqube
  type: LoadBalancer
